### ISSUE TITLE
Infinote support

### ISSUE THREAD

**Issue by ArneBab** [scymtym/rudel#3]
Is the infinote support working now? 

KDE just got an alpha quality kioslave to allow interaction via libinfinity and it would be really great if emacs rudel-mode would be ready to interact once every KDE text field gets realtime collaboration support.

http://scummos.blogspot.de/2013/04/collaborative-editing-in-kte-prototype.html

**Comment by scymtym** [comment]
I did not finish the infinote support before I stopped working on rudel. Sorry.
